[envs.default]
dependencies = [
  "coverage[toml] ~= 7.2",
  "pytest ~= 7.2",
  "pytest-cov ~= 4.0",
  "pytest-timeout ~= 2.1",
  "pytest-xdist ~= 3.1",
  "black ~= 23.1",
  "mypy == 0.981",
  "ruff ~= 0.0.254",
  "twine ~= 4.0",
]

[envs.default.scripts]
test = "pytest --cov-config pyproject.toml {args:test}"
typing = "mypy {args:src test}"
style = [
  "ruff {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "style",
]
lint = [
  "style",
  "typing",
]

[[envs.test.matrix]]
python = ["3.9", "3.10", "3.11"]

[envs.default.env-vars]
PIP_INDEX_URL="https://aws:{env:CODEARTIFACT_AUTH_TOKEN}@{env:CODEARTIFACT_DOMAIN}-{env:CODEARTIFACT_ACCOUNT_ID}.d.codeartifact.{env:REGION}.amazonaws.com/pypi/{env:CODEARTIFACT_REPOSITORY}/simple/"

[envs.codebuild.scripts]
build = "hatch build"

[envs.codebuild.env-vars]
PIP_INDEX_URL=""